# The need to put paths like "packages/**/*.movies.gql" is due to a bug
# in VSCode GraphQL, but this works well enough
# https://github.com/graphql/vscode-graphql/issues/242#issue-721757152

projects:
  docs:
    schema: .tina/__generated__/schema.gql
    documents:
      - ./**/*.tsx
      - ./**/*.gql
